version: '3.8'

services:
  kafka-consumer:
    build: .
    ports:
    # "8080" If we need to expose our service internally only
      - "8080:8080"
    networks:
      - backend-net
networks:
  backend-net:
    external: true
