version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: root         
      POSTGRES_PASSWORD: secret 
      POSTGRES_DB: wbdb 
    ports:
      - "5432:5432"  # Map PostgreSQL port to the host machine
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db_network
    restart: unless-stopped

volumes:
  pgdata:
    driver: local

networks:
  db_network:
    driver: bridge
