version: '3.8'

services:
  influxdb:
    image: influxdb:2.7.10
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_ORG=grafana
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - monitoring

  influxdbv1:
    image: influxdb:1.8
    container_name: influxdbv1
    ports:
      - "8085:8086"  # Map host port 8085 to container's port 8086
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_DB: influx
    volumes:
      - influxdb_data:/var/lib/influxdb  # Persist InfluxDB data on the host
    networks:
      - monitoring

  telegraf:
    image: telegraf:1.32
    container_name: telegraf
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc:/host/etc:ro
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  influxdb_data:
